name: Function Deploy
on: 
  push:
    branches:
      - main
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      app-name: pa200-project-covid-registrations
    steps:
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.0
