name: Function Deploy
on: 
  push:
    branches:
      - main
env:
  AZURE_FUNCTIONAPP_NAME: pa200-project-covid-registrations
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Azure Functions Action
        uses: Azure/functions-action@v1.4.0
        with:
          app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}
